### ISSUE TITLE
第1回MTG

### ISSUE THREAD

**Issue by nsuzuki7713** [haruto830/pflist-frontend#18]
忘れないように議題とかを追加して頂ければです！！

# 概要
- [ ] 日にち
  6/22 (土)
- [ ] 時間
  09:00～
- [ ] 場所
  * [yahoo lodge](https://lodge.yahoo.co.jp/)
- [ ] 参加者
  * 全員

# 議題
- 進捗確認
- プロダクトすり合わせ
- 設計を考える

**Comment by haruto830** [comment]
詳細設計の粒度を決める

**Comment by nsuzuki7713** [comment]
- 設計書作成の考え方統一
- 設計書の粒度をきめる
- 設計書の書き方を決める
- 開発の進め方を決める（レビュー等）

**Comment by haruto830** [comment]
### 第２フェーズでつくるものリスト
- 詳細画面
  - 検索機能
